### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sarob**
1. Implements #22 

1. Additional 5 more research wiki pages that are moved from the old README page to the wiki that will look like this 
image

### CODE REVIEW

**Comment by epowell101** [comment]
Could we still have a single landscape section?

**Comment by sarob** [comment]
@epowell101 advises that he wants to keep the README as is. Closing.

**Comment by epowell101** [comment]
No - I thought we could still have a single landscape page. I would be great to also have a classic project readme - if that makes sense

Evan

Evan Powell
415 377 9812
Twitter: @epowell101 ( http://www.twitter.com/epowell101 )

**Comment by sarob** [comment]
I may gotten confused with what you want for the README page. Reach out and we can talk it though. Sean ***@***.*** On Dec 9, 2022, at 20:04, Evan Powell ***@***.***> wrote:﻿
No - I thought we could still have a single landscape page. I would be great to also have a classic project readme - if that makes sense

Evan

Evan Powell
415 377 9812
Twitter: @epowell101 ( http://www.twitter.com/epowell101 )

**Comment by sarob** [comment]
Now that I have reread what you posted...

Is this more like what you are thinking 
README.md
image
 that points to either a wiki or repo page landscape.md
image

**Pull request closed without merging**
