### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by sarob**
developed from the conversation in devrel https://discord.com/channels/1037443230993743902/1052679517610709012

### CODE REVIEW

**Comment by sarob** [comment]
> * I would prefer having the preferred way of contributing is: come chat with us on discord to get access to the repo. Or create a fork and then do a pull request. I don't see why we would not accept that way as it is also safe and permissionless from ODC.

Forking is always an option. I was writing and thinking for the average beginner that would want to push directly to the origin repository and would be likely confused by describing forking. 

> * Labels can help sort out good first issues

Agreed. I included a URL for a GitHub help doc on it in the contributing file on line 29. 

> * Commit your update:
> * Commits should contain the number of the issue, you can do several commits before doing a pull request.
> * The pull request subject or description if needed should explain what has been done or added.

I am not sure if you are asking or telling me something here. I think you are referencing line 58. 

Let me know what else I can explain about the commit. Thanks!

**Comment by poupou-web3** [comment]
> Forking is always an option. I was writing and thinking for the average beginner that would want to push directly to the origin repository and would be likely confused by describing forking.
I have not contributed to many OSS but I thought it would be simpler for us not to manage all requests to access the repo. Both options should be mentioned

>I am not sure if you are asking or telling me something here. I think you are referencing line 58.
Yes I was referencing ligne 58:
> - Commit and push the changes once you are happy with them using an informative message. Always add the issue # into the description field as `#<number>`, e.g. the issue number is 32, so add `#32` in the description field. An issue is optional for a PR, but recommended.  The description field is also optional. 
> - We use repository branch protection rules that require ODC repositories only allow Pull Requests (PR), so Github Desktop will prompt you to create a PR.
I see it like that:
- You can do as many commits as you want on your branch until you are happy with them using an informative message. Always add the issue # into the description field as `#<number>`, e.g. the issue number is 32, so add `#32` in the description field. A good practice is to work on one issue at a time, therefore your commits should only contain one issue number.
(I personally prefer the issue number in the commit message and not in the description)
- When you are working on your branch you can push your changes as often as you want. Pushing allows you to save your changes on the remote repository and not only on your local changes
- Then when you are done and have pushed your changes to the remote repository. Create a pull request, An issue is optional for a PR, but recommended so anyone can refer to the issue you are solving.  The description field is also optional. 

I may be missing something here because the pull request is created when you want to merge your changes to the production branch, isn't it?

**Comment by sarob** [comment]
Sean ***@***.*** On Dec 21, 2022, at 04:32, poupou-web3 ***@***.***> wrote:﻿

Forking is always an option. I was writing and thinking for the average beginner that would want to push directly to the origin repository and would be likely confused by describing forking.
I have not contributed to many OSS but I thought it would be simpler for us not to manage all requests to access the repo. Both options should be mentioned


I am not sure if you are asking or telling me something here. I think you are referencing line 58.
Yes I was referencing ligne 58:

Commit and push the changes once you are happy with them using an informative message. Always add the issue # into the description field as #<number>, e.g. the issue number is 32, so add #32 in the description field. An issue is optional for a PR, but recommended.  The description field is also optional.
We use repository branch protection rules that require ODC repositories only allow Pull Requests (PR), so Github Desktop will prompt you to create a PR.
I see it like that:



You can do as many commits as you want on your branch until you are happy with them using an informative message. Always add the issue # into the description field as #<number>, e.g. the issue number is 32, so add #32 in the description field. A good practice is to work on one issue at a time, therefore your commits should only contain one issue number.(I personally prefer the issue number in the commit message and not in the description)Sounds good!
When you are working on your branch you can push your changes as often as you want. Pushing allows you to save your changes on the remote repository and not only on your local changesI’ll add this. 
Then when you are done and have pushed your changes to the remote repository. Create a pull request, An issue is optional for a PR, but recommended so anyone can refer to the issue you are solving.  The description field is also optional.I’ll incorporate to the paragraph shortly. 

I may be missing something here because the pull request is created when you want to merge your changes to the production branch, isn't it?I can include a bit more information to the above paragraph, like when you are ready to merge to the main branch. Thanks!

**Review by epowell101 — APPROVED** [review]
please do mention HackMD:  https://hackmd.io/

looks good!

**Pull request merged**
